# Generated by Django 5.0.4 on 2024-04-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_rename_like_user_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
