# Generated by Django 5.0.4 on 2024-04-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_pet', '0003_rename_post_petpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='petpost',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
