# Generated by Django 5.0.4 on 2024-04-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_pet', '0004_petpost_views_alter_petpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='petpost',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
