# Generated by Django 5.0.4 on 2024-04-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_pet', '0007_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='petpost',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
