# Generated by Django 5.0.4 on 2024-04-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_pet', '0008_petpost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petpost',
            name='likes',
        ),
    ]
