# Generated by Django 5.0.4 on 2024-04-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_pet', '0015_comment_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='petpost',
            name='tags',
            field=models.ManyToManyField(to='post_pet.tags'),
        ),
    ]
